version: '3.8'

services:
  queue-opt-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: queue-opt-frontend-app-dev
    ports:
      - '3030:3030'
    environment:
      - NODE_ENV=production
      - PORT=3030
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    networks:
      - queue-opt-network-dev

networks:
  queue-opt-network-dev:
    driver: bridge
